import { DM_Sans } from "next/font/google";
import "./globals.css";
import AnimatedCursor from "react-animated-cursor";

// Font
const dm_sans = DM_Sans({ subsets: ["latin"] });

// Provider
import Providers from "./providers";

// Components
import Navbar from "./components/navbar";

export const metadata = {
  title: "RegalLion Studios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} text-text-normal`}>
        <Providers>
          <Navbar />
          {/* <AnimatedCursor
            innerStyle={{
              backgroundColor: "black",
            }}
            outerStyle={{
              border: "3px solid black",
            }}
          /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
