import { Inter } from "next/font/google";
import "./globals.css";

// Font
const inter = Inter({ subsets: ["latin"] });

// Provider
import Provider from "./components/provider";

export const metadata = {
  title: "Verityx Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
