import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "lenis/dist/lenis.css";
import "./globals.css";

// Components
import Providers from "@/src/app/providers";

// UI
import { Navbar } from "@/src/components/layout";

const barlowFont = Barlow_Condensed({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlowFont.variable} antialiased`}>
      <body className="min-h-screen flex flex-col ">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
